### ISSUE TITLE
New Feature Discussion: Event Listeners

### ISSUE THREAD

**Issue by David-Melo** [pedro-lb/react-onesignal#2]
Hello, I already made a pull request to add a feature I needed and now I'm facing another need but I'm not sure how we could go about this. OneSignal provides several event listeners that are registered within the PUSH function.

```
OneSignal.push(function() {
  // Occurs when the user's subscription changes to a new value.
  OneSignal.on('subscriptionChange', function (isSubscribed) {
    console.log("The user's subscription state is now:", isSubscribed);
  });
});
```

It would be nice if when initializing react-onesignal we could pass in some functions to attach to those listeners. Since react-onesignal just prints out a string for initializing OneSignal, I'm not even sure this would be possible.

**Comment by gabrielnaoto** [comment]
Maybe we could have an array of events? 
And then `react-onesignal` could iterate and render then in the initialization.

```
[
  {"event1", callbackA},
  {"event2", callbackB},
]

**Comment by pedro-lb** [comment]
Looks good @gabrielnaoto! I think this solves the problem

**Comment by slothluvchunk** [comment]
This is behavior we'd definitely like to use, and I may be able to carve out some time to help implement if there's any desire to get this done in the short term.

**Comment by pedro-lb** [comment]
Hey there @slothluvchunk !

Feel free to submit a PR implementing this feature. I'm available to help you if you need!

**Comment by slothluvchunk** [comment]
I'm not sure about the best way to structure this (just looking through the code a bit), so I'd likely need some guidance there, but am game to help.
In the meantime, I've created a "sendTag()" method that's working on my local, and allows use of the native `sendTag` functionality, similar to `setEmail()`.

ex:
`ReactOneSignal.sendTag('someTag', 'someValue');`

**Comment by slothluvchunk** [comment]
@pedro-lb  - Just following up on my last comment, I've pushed up a PR to implement the sendTag/sendTags methods for the short-term. 
I'd still like to help implement the event listener functionality as well, I'll just need some help in structuring it properly.

**Comment by slothluvchunk** [comment]
@pedro-lb , et al., 
Just a quick update - I've got a working version locally of the events/callback array.
After defining the event name and callback in the code and passing it in as is done with `options`, the `events` array is looped over, and wrapped in some js, and injected with the rest of the script body, allowing the event listeners to load and function normally. 
It will need some cleanup and more testing, but I'm happy to do that and push up a PR if it's something you've got time to take a look at.

**Comment by pedro-lb** [comment]
Currently in analysis - https://github.com/pedro-lb/react-onesignal/pull/6

**Comment by pedro-lb** [comment]
https://github.com/pedro-lb/react-onesignal/releases/tag/1.2.1
