### ISSUE TITLE
Wrong type on event callback.

### ISSUE THREAD

**Issue by MakhBeth** [pedro-lb/react-onesignal#22]
Hi! 
I've copy-pasted the example of the event handler
```ts
        [
          {
            listener: 'once',
            event: 'subscriptionChange',
            callback: isSubscribed => {
              if (isSubscribed === true) {
                console.log('The user subscription state is now:', isSubscribed)
              }
            },
          },
        ]
```

 but I have a TS error:
```
(property) IOneSignalEvent.callback: IOneSignalEventCallback
Property 'callback' is missing in type '(isSubscribed: any) => void' but required in type 'IOneSignalEventCallback'.ts(2741)
```

TS wants an object like `{callback: {callback: (result: any) => any}}` instead of a simple `{callback: (result: any) => any}`

Here the d.ts file that causes the issue
https://github.com/pedro-lb/react-onesignal/blob/a6b249b71ce6ebc4f2091ad0d2f70b1a709bbc4c/package/src/oneSignal.types.ts#L61

Thank you for the beautiful project saved me a ton of time :)

**Comment by nqduy96** [comment]
nice!
