### ISSUE TITLE
react-onesignal-not-working

### ISSUE THREAD

**Issue by briancaldass** [pedro-lb/react-onesignal#27]
it's not working

I have the next one message:
![image](https://user-images.githubusercontent.com/16884130/104057041-6d57b500-51bf-11eb-99b5-71a4dc3420df.png)

**Comment by statico** [comment]
You have to [download the OneSignal Service Worker files](https://github.com/OneSignal/OneSignal-Website-SDK/releases/download/https-integration-files/OneSignal-Web-SDK-HTTPS-Integration-Files.zip) and (by default) serve them from the root of your application.

More information: https://documentation.onesignal.com/docs/onesignal-service-worker-faq

**Comment by pedro-lb** [comment]
That's correct, @statico. Thanks for the response!

I'll close this issue, but feel free to respond if there is any other problem actually related to `react-onesignal`.
