### ISSUE TITLE
Onesignal setExtarnalId

### ISSUE THREAD

**Issue by tamerayas** [pedro-lb/react-onesignal#3]
Hi. I need to use setExternalId in my project. Can u implement this method to your component? Please help me about that.

**Comment by pedro-lb** [comment]
Hey there @tamerayas!

I'll take a look on this as soon as possible.

**Comment by tamerayas** [comment]
Hi. Is there any improvement about that ?

**Comment by pedro-lb** [comment]
Hey there @tamerayas!

Just released a new version with this: https://github.com/pedro-lb/react-onesignal/releases/tag/1.1.19
