### ISSUE TITLE
No Document Object When Rendering Server Side

### ISSUE THREAD

**Issue by slothluvchunk** [pedro-lb/react-onesignal#4]
Hi, 
We're running a headless wordpress site with react on the front end, and I was hoping to be able to use this package to easily incorporate OneSignal. 
We utilize isomorphic rendering, and it looks like there might be an issue with server side rendering with react-onesignal, where it requires a document object when none exists. 

Do you know of any workaround for this (or is it different issue altogether)?

This is currently in a component by itself, just doing the basic initialization:

'import ReactOneSignal from 'react-onesignal';
const OneSignal = (props) => {
  const options = {
    notifyButton: {
      enable: true,
    },
  };
  ReactOneSignal.initialize('<app ID>', options)
  return (
    // return stuff
  );
};
export default OneSignal;`

In the console, this yields the following:
` render:error { url: '/',
  render:error   err:
  render:error    ReferenceError: document is not defined
  render:error        at Object.initialize (/Users/me/site//node_modules/react-onesignal/src/oneSignal.ts:149:3)
  render:error        at initialize (/Users/me/site//build/server/webpack:/components/oneSignal/index.js:87:20)
  render:error        at processChild (/Users/me/site//node_modules/react-dom/cjs/react-dom-server.node.development.js:2871:14)
  render:error        at resolve (/Users/me/site//node_modules/react-dom/cjs/react-dom-server.node.development.js:2795:5)
  render:error        at ReactDOMServerRenderer.render (/Users/me/site//node_modules/react-dom/cjs/react-dom-server.node.development.js:3185:22)
  render:error        at ReactDOMServerRenderer.read (/Users/me/site//node_modules/react-dom/cjs/react-dom-server.node.development.js:3144:29)
  render:error        at renderToString (/Users/me/site//node_modules/react-dom/cjs/react-dom-server.node.development.js:3629:27)
  render:error        at _callee$ (/Users/me/site//build/server/webpack:/server/serverRenderer.js:85:33)
  render:error        at tryCatch (/Users/me/site//node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:62:40)
  render:error        at Generator.invoke [as _invoke] (/Users/me/site//node_modules/@babel/polyfill/node_modules/regenerator-runtime/runtime.js:288:22) } +0ms`

**Comment by slothluvchunk** [comment]
Just updating - this may have been resolved by simply refactoring the component to initialize within a componentDidMount() callback. 
I do get the badge now, though the subscribe/unsubscribe functionality isn't working consistently, yet.

**Comment by slothluvchunk** [comment]
I'm going to close this for now - the original issue is solved, and it seems that other issues I was experiencing are not related to this at all.

**Comment by pedro-lb** [comment]
Hey there @slothluvchunk ,

Thanks for the contribution!

Did you need to apply any changes to `react-onesignal` to solve your issue? If so, we can incorporate these changes to make sure that it will work with other users too.

Best regards,

**Comment by statico** [comment]
If it helps anybody, this is what I ended up with for my own `useOneSignal` hook using Next.js, which does isomorphic/SSR:

```typescript
import getConfig from "next/config"

const { publicRuntimeConfig } = getConfig()

export const useOneSignal = (userId?: string): void => {
  // react-onsignal tries to use a global `document` variable, so we can only
  // use it in the client side. Luckily this method doesn't trigger any "wrong
  // number of hooks" errors either.
  if (!process.browser) return
  const module = require("react-onesignal")
  const OneSignal = module.default
  const { useOneSignalSetup } = module

  const oneSignalAppId = publicRuntimeConfig?.oneSignalAppId

  OneSignal.initialize(oneSignalAppId, {
    allowLocalhostAsSecureOrigin: process.env.NODE_ENV !== "production",
  })

  useOneSignalSetup(() => {
    // These checks have to be done within the useOneSignalSetup hook's
    // callback, otherwise you'll get "wrong number of hooks" errors.
    if (!process.browser) return
    if (!oneSignalAppId || !userId) return
    OneSignal.setExternalUserId(userId)
    OneSignal.registerForPushNotifications()
  })
}
```

**Comment by CPROps** [comment]
> Hey there @slothluvchunk ,
> 
> Thanks for the contribution!
> 
> Did you need to apply any changes to `react-onesignal` to solve your issue? If so, we can incorporate these changes to make sure that it will work with other users too.
> 
> Best regards,

Sorry I missed this question, @pedro-lb!
I did not need to make any changes to the package. We were able to make things work in a class component, simply forcing this to load client-side within `componentDidMount()`.
Another thing that helped us was using `express.static()` [<docs>](https://expressjs.com/en/starter/static-files.html) to make the library publicly available.

**Comment by slothluvchunk** [comment]
> Hey there @slothluvchunk ,
> 
> Thanks for the contribution!
> 
> Did you need to apply any changes to `react-onesignal` to solve your issue? If so, we can incorporate these changes to make sure that it will work with other users too.
> 
> Best regards,

Sorry I missed this question, @pedro-lb!
I did not need to make any changes to the package. We were able to make things work in a class component, simply forcing this to load client-side within `componentDidMount()`.
Another thing that helped us was using `express.static()` [<docs>](https://expressjs.com/en/starter/static-files.html) to make the library publicly available.
